spring:
  datasource:
    url: jdbc:mysql://bigdata01:3306/manager?user=root&password=123456&useUnicode=true&characterEncoding=utf8
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
server:
  context-path: /manager
  port: 8081
